# Generated by Django 4.2 on 2025-11-14 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('año', models.IntegerField()),
                ('director', models.CharField(max_length=255)),
                ('categoria', models.CharField(max_length=100)),
                ('sinapsis', models.TextField()),
            ],
        ),
    ]
