# Generated by Django 4.2 on 2025-11-14 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_rename_sinapsis_movie_sinopsis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='año',
            new_name='Año',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='categoria',
            new_name='Categoría',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='director',
            new_name='Director',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='sinopsis',
            new_name='Sinapsis',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='titulo',
            new_name='Título',
        ),
        migrations.AddField(
            model_name='movie',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='movies/'),
        ),
    ]
