# Generated by Django 4.2 on 2025-11-14 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_rename_año_movie_año_and_more'),
        ('movies', '0004_peliculas_iniciales'),
    ]

    operations = [
    ]
